dataset: ESOL
sampler: canonical
split_ratio: 0.8,0.1,0.1
split: scaffold
model: GCN
result_path: 'logs/esol_fedavg_gcn'
metric: 'rmse'
num_epochs: 100
num_clients: 3
fraction_fit: 0.5
task_names: HIV_active
featurizer_type: 'canonical'
pretrain: False
batch_size: 32
batchnorm: False
dropout: 0.1
gnn_hidden_feats: 64
lr: 0.001
num_gnn_layers: 3
patience: 1000
predictor_hidden_feats: 16
residual: False
weight_decay: 0.00001
node_out_feats: 32
n_tasks: 1
num_workers: 1
print_every: 20