dataset: HIV
split_ratio: 0.8,0.1,0.1
split: scaffold
model: GCN
result_path: 'logs/HIV_GCN'
metric: 'roc_auc_score'
num_epochs: 1000
task_names: HIV_active
featurizer_type: 'canonical'
pretrain: False
batch_size: 32
batchnorm: False
dropout: 0.18118350615245202
gnn_hidden_feats: 64
lr: 0.001
num_gnn_layers: 3
patience: 3
predictor_hidden_feats: 16
residual: False
weight_decay: 1.5353642545259472e-05
node_out_feats: 32
n_tasks: 1
num_workers: 16
print_every: 20