dataset: Tox21
split_ratio: 0.8,0.1,0.1
split: scaffold
model: MPNN
result_path: 'logs/Tox21_MPNN'
metric: 'roc_auc_score'
num_epochs: 1000
task_names: 'NR-ER'
featurizer_type: 'canonical'
pretrain: False
batch_size: 128
batchnorm: False
node_out_feats: 32
edge_hidden_feats: 64
dropout: 0.18118350615245202
gnn_hidden_feats: 64
lr: 0.03531524773979991
num_gnn_layers: 3
patience: 3
num_step_set2set: 3
num_layer_set2set: 3
num_step_message_passing: 1
predictor_hidden_feats: 16
weight_decay: 3.520879880952354e-05
n_tasks: 12
num_workers: 16
print_every: 20